unstable_features = true
indent_style = "Visual"
use_small_heuristics = "Max"
condense_wildcard_suffixes = true
fn_args_layout = "Tall"
max_width = 100
struct_field_align_threshold = 50
fn_single_line = true
format_code_in_doc_comments = true
format_strings = true
merge_derives = true
